name: cd

on:
  push:
    branches: [develop]

jobs:
  release-next:
    name: release-next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: install tesseract
        run: apt-get install tesseract-ocr tesseract-ocr-eng tesseract-ocr-deu
      - run: npm install
      - run: npx lerna run build
      - run: npx lerna run test
      - run: npx lerna run test:e2e
      - run: npx lerna run build:release
      - run: npm run lerna:publish-next
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}