name: ci

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
  pull_request:

env:
  CHROMEDRIVER_FILEPATH: "/usr/local/share/chrome_driver/chromedriver"

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm install
      - run: npx lerna run build
      - run: npm t -- --runInBand --ci --bail --forceExit
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-20.04
    steps:
      - name: Install prerequisites
        run: sudo apt-get install build-essential python libxtst-dev libpng++-dev libxt-dev libxinerama-dev tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng xvfb
        shell: bash
      - uses: actions/checkout@v2.4.2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm install
      - run: npx lerna run build
      - name: execute E2E tests
        run: |
          cd ./packages/e2e
          xvfb-run --server-args="-screen 0, 1920x1080x24" npm run test:e2e
        shell: bash
        env:
          LOG_MODE: ci
      - name: save error screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: error-screenshot
          path: |
            ./packages/e2e/e2e-suite/_logs/_screenshots
