name: ci

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - 'release/**'
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - run: npx lerna run test