name: ci

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
      - "release/**"
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - run: npm t -- --runInBand --ci --bail
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-20.04
    steps:
      - name: Install prerequisites
        run: sudo apt-get install build-essential python libxtst-dev libpng++-dev libxt-dev libxinerama-dev tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng xvfb
        shell: bash
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - name: execute E2E tests
        run: |
          cd ./packages/e2e
          xvfb-run --server-args="-screen 0, 1920x1080x24" npm run test:e2e
        shell: bash
        env:
          SAKULI_LICENSE_KEY: ${{ secrets.SAKULI_LICENSE_KEY }}
          LOG_MODE: ci
      - name: save error screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: error-screenshot
          path: |
            ./packages/e2e/e2e-suite/_logs/_screenshots
            ./packages/e2e/ocr-screenshot.png
