name: ci

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
      - "release/**"
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - run: npx lerna run test
  e2e-test:
    name: e2e-test
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install prerequisites
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get install build-essential python libxtst-dev libpng++-dev libxt-dev libxinerama-dev tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng xvfb
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install tesseract
          elif [ "$RUNNER_OS" == "Windows" ]; then
            nuget install Tesseract
            echo "%userprofile%\.nuget\packages" >> $GITHUB_PATH
          fi
        shell: bash
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - name: execute E2E tests
        run: |
          cd ./packages/e2e
          EXECUTE_TESTS="npm run test:e2e"
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run --server-args="1920x1080x24" ${EXECUTE_TESTS}
          else
            ${EXECUTE_TESTS}
          fi
        shell: bash
        env:
          SAKULI_LICENSE_KEY: ${{ secrets.SAKULI_LICENSE_KEY }}
