name: ci

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
      - "release/**"
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - run: npx lerna run test
  e2e-test:
    name: e2e-test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get install build-essential python libxtst-dev libpng++-dev xvfb
               xvfb-run
          fi
        shell: bash
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npx lerna run build
      - run: npx lerna run test:e2e
        env:
          SAKULI_LICENSE_KEY: ${{ secrets.SAKULI_LICENSE_KEY }}
