name: release-version

on:
  push:
    tags:
      - v*.*.*

env:
  CHROMEDRIVER_FILEPATH: "/usr/local/share/chrome_driver/chromedriver"

jobs:
  release-version:
    name: release-version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Use Node.js 16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install prerequisites
        run: sudo apt-get install build-essential python libxtst-dev libpng++-dev libxt-dev libxinerama-dev tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng xvfb
        shell: bash
      - name: Set SAKULI_VERSION according to tag
        run: echo "SAKULI_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - run: npm install
      - run: npx lerna run build
      - run: npm t -- --runInBand --ci --bail --forceExit
      - name: execute E2E tests
        run: |
          cd ./packages/e2e
          xvfb-run --server-args="-screen 0, 1920x1080x24" npm run test:e2e
        shell: bash
        env:
          LOG_MODE: ci
      - name: save error screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2.3.1
        with:
          name: error-screenshots
          path: |
            ./packages/e2e/e2e-suite/_logs/_screenshots
      - run: npx lerna run build
      - run: npm run lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
