name: release-version

on:
  push:
    tags:
      - v*.*.*

jobs:
  release-version:
    name: release-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: install tesseract
        run: apt-get install tesseract-ocr tesseract-ocr-eng tesseract-ocr-deu
      - name: Set SAKULI_VERSION according to tag
        run: echo "SAKULI_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - run: npm install
      - run: npx lerna run build
      - run: npx lerna run test
      - run: npx lerna run test:e2e
      - run: npx lerna run build:release
      - run: npx lerna version --no-git-tag-version --no-push -y --exact ${SAKULI_VERSION}
      - run: npm run lerna:publish
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
