name: release-version

on:
  push:
    tags:
      - v*.*.*

jobs:
  release-version:
    name: release-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Set SAKULI_VERSION according to tag
        run: echo "SAKULI_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - run: npm install
      - run: lerna run build
      - run: lerna run test
      - run: lerna run build:release
      - run: npm run lerna:publish
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
